apiVersion: v1
kind: Service
metadata:
  name: webapp-rosa
  namespace: gitops-app
spec:
  selector:
    app: webapp-rosa
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-vermelho
  namespace: gitops-app
spec:
  selector:
    app: webapp-vermelho
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-verde
  namespace: gitops-app
spec:
  selector:
    app: webapp-verde
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-azul
  namespace: gitops-app
spec:
  selector:
    app: webapp-azul
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: gitops-app
spec:
  selector:
    app: haproxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
